### ISSUE TITLE
Feat: add regexp format string to replace

### ISSUE THREAD

**Issue by snowyu** [offline-ai/cli#15]
eg,

```yaml
user: |-
  Output the result and wrap it with '<RESULT></RESULT>'
assitant: "[[Answer]]"
---
user: "base on the content: /<RESULT>(.+)</RESULT>/:Answer"
```
