### ISSUE TITLE
Feat: add import configuration to import functions and declarations in other script file

### ISSUE THREAD

**Issue by snowyu** [offline-ai/cli#18]
Note:

* the default is js module if not extension name provided.
* The relative path is the folder of the current ai script, not the CWD(current working dir
* When the imported declaration is a function, it automatically adds the prefix "$" to function names without a prefix

Import all functions of a script file:

```yaml
---
import: "./your_script.js"
---
```

Import many files Use Array Format:

```yaml
---
import:
  - "js_package_name"
  - "js/script/path.js": ['func1', 'func2'] # Import only the specified functions
  - 'ruby-funcs.rb'
  - "agent.ai.yaml": "asName" # Import the script and rename it to "$asName"
---
```

Use Object Format:

```yaml
---
import: # Object Format
  "js_package_name": "*"
  "js/script/path.js": ['func1', 'func2']
  "agent.ai.yaml": "asName"
---
```
